
 #Database Configuration
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
  datasource:
    url: jdbc:mysql://localhost:3306/sm_appln
    username: root		
    password: admin1234
    driverClassName: com.mysql.jdbc.Driver
#Logger Configuration
logging:
  file: D:\\socialMediaLogs\\appln.log
  pattern:
     console: "%d %-5level %logger : %msg%n"
     file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    org.springframework.security: INFO
    com.lambya: INFO
      
file: 
  imageStoragePath: "D:\\correct_way\\images"  


    